Before running with the attack tool, we need to make sure dc_shell (Synopsys Design Compiler), Verilator, and ABC tools are available.

Please check more information about Verilator tool by visiting this link: https://www.veripool.org/verilator/

Please check more information about ABC tool by visiting this link: https://people.eecs.berkeley.edu/~alanmi/abc/

1. Please download NangateOpenCellLibrary.db, and save it in the path "./lib/NangateOpenCellLibrary.db". The source can be downloaded from this link: https://si2.org/open-cell-library/

2. Before running FuncTeller, we need to construct some directories:
	mkdir ./middle_process/
	mkdir ./middle_process/miter_circuit_accuracy/
	mkdir ./middle_process/predicted_circuit/
	mkdir ./middle_process/predicted_circuit_entire/
	mkdir ./middle_process/RTL_constraint/

3. Go to "./original_bench/oracle/split_to_cone/" directory to generate all single cones. Run with the command
	python3 control_all.py <path to original "fpga_oracle.bench" (Please keep the name style of the file)>
such as, "python3 control_all.py ~/csaw_2021/security_analysis_resources/set1/set1_1/fpga_oracle.bench"

4. Go to "./original_bench/oracle/" directory to generate oracles. The command is
	python3 run_create_oracles.py ./split_to_cone/oralce.bench 

After running this command, please check and ensure all cones' oracles are generated.

5. Go to "./coding/" to generate RTL constraint files. The command is 
	python3 generate_RTL_constraint.py ../original_bench/oracle/split_to_cone/oracle.bench <max_num_process> <user_id>
such as, "python3 generate_RTL_constraint.py ../original_bench/oracle/split_to_cone/oracle.bench 50 <user_id>". Usually, the max_num_process is decided by the license of dc_shell.

After running this command, please check the status of dc_shell and RTL constraint netlist files. Please ensure that all RTL constraint netlists are generated by checking inside the "./middle_process/RLT_constraint/" directory. The total number of RTL constraint files is the same as the input size.

6. Go to "./coding/" to launch attacks. Make sure "pycosat" package is installed. The command is 
	./run_entire ../original_bench/oracle/split_to_cone/oracle.bench <converge_p> <d_0> <time_constraint (second)> <max_num_process> <user_id>
such as, "./run_entire ../original_bench/oracle/split_to_cone/oracle.bench 50 2 3600 50 <user_id>". Ususally, "max_num_process" is decided by the number of threats can be ultilzed in the platform.
The prediction cone (.bench and .pla) is saved in "./middle_process/predicted_circuit/"directory. The entire predicted circuit is save in "./middle_process/predicted_circuit_entire/" directory.
